refactor: upgrade contracts to solc v0.8.17
witnet/elliptic-curve-solidity pull request #35
Opened 2023-06-06 15:40 UTC by guidiaz

Close #33.

2023-06-09 17:34 UTC, aesedepece approved these changes

2023-06-15 17:01 UTC, aesedepece requested changes
Tests are not passing for this :cry:

2023-06-16 09:19 UTC, guidiaz commented
Indeed, I mentioned this fact in the related issue. The fix of those tests will have to be solved by #36. The scope of #33 was to upgrade to Solc v0.8.17 compiler, and this has been already accomplished.

2023-06-16 10:55 UTC, aesedepece approved these changes

2023-06-16 11:01 UTC, merged

2023-06-16 11:01 UTC, aesedepece commented
@guidiaz gotcha. Let me merge this then.